### PR TITLE
replaced SockJS with WebSockets

### PR DESCRIPTION
**Pull request by antondalgren**

### CODE REVIEW

**Comment by johanrhodin** [comment]
Did you verify that it works with a 3.7.x cluster?

**Comment by antondalgren** [comment]
Launched a 3.7 cluster and got it working!

**Review by carlhoerberg — APPROVED** [review]
Not `wss` ?

**Comment by antondalgren** [comment]
@carlhoerberg it will automatically add the last s depending on if the CLOUDAMQP_URL is amqps:// or amqps://

**Pull request merged**
